name: Project Submission
description: "Share your project with us to get a digital badge and win prizes!"
title: "Project: <short description>"
body:
  - type: input
    id: name
    attributes:
      label: Project Name
      description: Name of your project
    validations:
      required: true
  - type: textarea
    id: description
    attributes:
      label: Description
      description: Provide a short description of your agentic application. Who can benefit from your app?
    validations:
      required: true
  - type: checkboxes
    id: tags
    attributes:
      label: Language & Framework
      description: Check any languages or frameworks used for your agentic application.
      options:
        - label: Python
          required: false
        - label: C#
          required: false 
        - label: Java
          required: false  
        - label: JavaScript/TypeScript
          required: false 
          required: false
        - label: Microsoft Copilot Studio
          required: false 
        - label: Microsoft 365 Agents SDK
          required: false 
        - label: Azure AI Agent Service
          required: false 
  - type: input
    id: url_repo
    attributes:
      label: Project Repository URL
      description: URL of the GitHub repo with your project
    validations:
      required: true
  - type: input
    id: url_endpoint
    attributes:
      label: Deployed Endpoint URL
      description: URL of a deployed endpoint (if it can be publicly shared, not for private data)
    validations:
      required: false
  - type: input
    id: video
    attributes:
      label: Project Video
      description: A short demo video of your project
    validations:
      required: true
  - type: input
    id: teammembers
    attributes:
      label: Team Members
      description: Comma-separated list of GitHub users who worked on this project
    validations:
      required: true
  - type: checkboxes
    id: register
    attributes:
      label: Registration Check
      description: Confirm that your team has filled out the [registration form](https://developer.microsoft.com/reactor/events/25323/), we will not be able to confirm prizes if you don't! 
      options:
        - label: My team has completed the registration form.
          required: true